import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Bartera Design System
        'bt-background': '#FAFAF9',
        'bt-surface': '#FFFFFF',
        'bt-surface-secondary': '#F7F6F4',
        'bt-surface-tertiary': '#F1F0ED',
        'bt-border': '#E7E5E0',
        'bt-border-light': '#F0EFEB',
        'bt-text-primary': '#2C2B27',
        'bt-text-secondary': '#6B6A65',
        'bt-text-tertiary': '#9B9A94',
        'bt-text-muted': '#C5C4BF',
        'bt-accent': '#FF6B4A',
        'bt-accent-light': '#FFF1EE',
        'bt-accent-dark': '#E55A41',
        'bt-accent-darker': '#CC4A33',
        'bt-teal': '#0EA5A5',
        'bt-teal-light': '#E6F7F7',
        'bt-teal-dark': '#0D8A8A',
        'bt-success': '#10B981',
        'bt-success-light': '#D1FAE5',
        'bt-error': '#DC2626',
        'bt-error-light': '#FEE2E2',
        'bt-warning': '#D97706',
        'bt-warning-light': '#FEF3C7',
        'bt-want': '#0EA5A5',
        'bt-like': '#FF6B4A',
        'bt-match': '#10B981',
        'bt-pass': '#9B9A94',

        // Legacy compatibility
        'ig-background': '#fafafa',
        'ig-card': '#ffffff',
        'ig-border': '#dbdbdb',
        'ig-border-light': '#efefef',
        'ig-primary': '#262626',
        'ig-secondary': '#737373',
        'ig-tertiary': '#8e8e8e',
        'ig-link': '#00376b',
        'ig-like': '#ed4956',
        'ig-want': '#f59e0b',
        'ig-want-active': '#d97706',
        background: '#fafafa',
        card: '#ffffff',
        border: '#dbdbdb',
        accent: '#FF6B4A',
        'accent-hover': '#E55A41',
        want: '#0EA5A5',
        'want-hover': '#0D8A8A',
        like: '#FF6B4A',
        muted: '#6B6A65',
        foreground: '#2C2B27',
        secondary: '#F7F6F4',
      },
      fontFamily: {
        outfit: ['Outfit', 'sans-serif'],
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      spacing: {
        'ig-header': '56px',
        'ig-bottom': '64px',
      },
    },
  },
  plugins: [],
};
export default config;
